#########################################################################
#      Copyright (C) 2020        Sebastian Francisco Colomar Bauza      #
#      SPDX-License-Identifier:  GPL-2.0-only                           #
#########################################################################
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: redis-webui
  namespace: dockercoins
spec:
  podSelector:
    matchLabels:
      service: redis
  ingress:
    - 
      ports:
        - 
          protocol: TCP
          port: 6379
      from:
        - 
          namespaceSelector:
            matchLabels:
              namespace: dockercoins
        - 
          podSelector:
            matchLabels:
              service: webui
  policyTypes:
    - 
      Ingress
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: redis-worker
  namespace: dockercoins
spec:
  podSelector:
    matchLabels:
      service: redis
  ingress:
    - 
      ports:
        - 
          protocol: TCP
          port: 6379
      from:
        - 
          namespaceSelector:
            matchLabels:
              namespace: dockercoins
        - 
          podSelector:
            matchLabels:
              service: worker
  policyTypes:
    - 
      Ingress
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: webui
  namespace: dockercoins
spec:
  podSelector:
    matchLabels:
      service: webui
  ingress:
    - 
      ports:
        - 
          protocol: TCP
          port: 8080
      from:
        - 
          namespaceSelector:
            matchLabels:
              namespace: dockercoins
        - 
          podSelector: {}
  policyTypes:
    - 
      Ingress
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: rng
  namespace: dockercoins
spec:
  podSelector:
    matchLabels:
      service: hasher
  ingress:
    - 
      ports:
        - 
          protocol: TCP
          port: 8080
      from:
        - 
          namespaceSelector:
            matchLabels:
              namespace: dockercoins
        - 
          podSelector:
            matchLabels:
              service: worker
  policyTypes:
    - 
      Ingress
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: hasher
  namespace: dockercoins
spec:
  podSelector:
    matchLabels:
      service: hasher
  ingress:
    - 
      ports:
        - 
          protocol: TCP
          port: 8080
      from:
        - 
          namespaceSelector:
            matchLabels:
              namespace: dockercoins
        - 
          podSelector:
            matchLabels:
              service: worker
  policyTypes:
    - 
      Ingress
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: rng
  namespace: dockercoins
spec:
  selector:
    matchLabels:
      service: rng
  template:
    metadata:
      labels:
        service: rng
    spec:
      containers:
      -
        image: secobau/dockercoins:rng-1.4
        name: rng
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hasher
  namespace: dockercoins
spec:
  replicas: 1
  selector:
    matchLabels:
      service: hasher
  template:
    metadata:
      labels:
        service: hasher
    spec:
      containers:
      -
        image: secobau/dockercoins:hasher-1.4
        name: hasher
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: dockercoins
spec:
  replicas: 1
  selector:
    matchLabels:
      service: redis
  template:
    metadata:
      labels:
        service: redis
    spec:
      containers:
      -
        image: redis
        name: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webui
  namespace: dockercoins
spec:
  replicas: 1
  selector:
    matchLabels:
      service: webui
  template:
    metadata:
      labels:
        service: webui
    spec:
      containers:
      -
        image: secobau/dockercoins:webui-1.4
        name: webui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: dockercoins
spec:
  replicas: 1
  selector:
    matchLabels:
      service: worker
  template:
    metadata:
      labels:
        service: worker
    spec:
      containers:
      -
        image: secobau/dockercoins:worker-1.5
        name: worker
---
apiVersion: v1
kind: Service
metadata:
  name: hasher
  namespace: dockercoins
spec:
  ports:
  - 
    port: 8080
  selector:
    service: hasher
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: dockercoins
spec:
  ports:
  - 
    port: 6379
  selector:
    service: redis
---
apiVersion: v1
kind: Service
metadata:
  name: rng
  namespace: dockercoins
spec:
  ports:
  - 
    port: 8080
  selector:
    service: rng
---
apiVersion: v1
kind: Service
metadata:
  name: webui
  namespace: dockercoins
spec:
  ports:
  -
    port: 8080
  selector:
    service: webui
---
#########################################################################
